export const INPUT_CHANGE = 'home/INPUT_CHANGE'
export const INPUT_CLEAR = 'home/INPUT_CLEAR'
export const RECIPES_FETCH = 'recipes/FETCH'
export const RECIPES_FETCH_SUCCESS = 'recipes/FETCH_SUCCESS'
export const RECIPES_FETCH_ERROR= 'recipes/FETCH_ERROR'